baseURL = "https://OmegaPsiJHU.github.io/"
languageCode = "en-us"
title = "Omega Psi at JHU"
theme = "kube"
description = "Website of the Johns Hopkins University chapter of Omega Psi, the undergratuate society for cognitive science."
Paginate = 4
[Params]
  facebook = "https://www.facebook.com/jhu.omegapsi/"
  instagram = "https://www.instagram.com/jhu.omegapsi/"

[[menu.main]]
  name = "Who We Are"
  identifier = "who"
  weight = -100
  url = "/about/"
[[menu.main]]
  name = "Board"
  parent = "who"
  weight = -100
  url = "/board/"
[[menu.main]]
    name = "News"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "About Us"
    parent = "who"
    weight = -100
    url = "/about/"
[[menu.main]]
    name = "Contact Us"
    weight = 100
    url = "/contact/"
[[menu.main]]
    name = "Conference"
    weight = 50
    identifier = "conference"
    url = "/conference/"
[[menu.main]]
    name = "Past Conferences"
    weight = 100
    parent = "conference"
    url = "/conference/past/"

